"""Add Google OAuth fields

Revision ID: 278f5ab8949e
Revises: b1f2c3d4a5b6
Create Date: 2026-08-17 12:45:16.635885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '278f5ab8949e'
down_revision: Union[str, Sequence[str], None] = 'b1f2c3d4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('writes')
    op.drop_table('checkpoints')
    op.add_column('users', sa.Column('google_id', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_refresh_token', sa.String(), nullable=True))
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'google_refresh_token')
    op.drop_column('users', 'google_access_token')
    op.drop_column('users', 'google_id')
    op.create_table('checkpoints',
    sa.Column('thread_id', sa.TEXT(), nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), nullable=False),
    sa.Column('parent_checkpoint_id', sa.TEXT(), nullable=True),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('checkpoint', sa.BLOB(), nullable=True),
    sa.Column('metadata', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id')
    )
    op.create_table('writes',
    sa.Column('thread_id', sa.TEXT(), nullable=False),
    sa.Column('checkpoint_ns', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('checkpoint_id', sa.TEXT(), nullable=False),
    sa.Column('task_id', sa.TEXT(), nullable=False),
    sa.Column('idx', sa.INTEGER(), nullable=False),
    sa.Column('channel', sa.TEXT(), nullable=False),
    sa.Column('type', sa.TEXT(), nullable=True),
    sa.Column('value', sa.BLOB(), nullable=True),
    sa.PrimaryKeyConstraint('thread_id', 'checkpoint_ns', 'checkpoint_id', 'task_id', 'idx')
    )
    # ### end Alembic commands ###
