"""Add default_spreadsheet_id

Revision ID: d9da189bb494
Revises: 278f5ab8949e
Create Date: 2026-08-17 15:07:09.710830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9da189bb494'
down_revision: Union[str, Sequence[str], None] = '278f5ab8949e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('default_spreadsheet_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'default_spreadsheet_id')
    # ### end Alembic commands ###
